services:

  # Backend Database
  postgres:
    image: postgres:trixie
    container_name: postgresql
    restart: unless-stopped
    secrets:
      - pg_host_password
    environment:
      # Default user is the host server
      POSTGRES_USER: host
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_host_password
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  flyway:
    image: flyway/flyway:12-alpine
    container_name: flyway
    secrets: 
      - pg_host_password
    # Why would they not let you pull from a password file by default??
    entrypoint: /bin/sh
    command: -c "
      flyway
        -url=jdbc:postgresql://postgres:5432/postgres
        -user=host 
        -password=\$$(cat /run/secrets/pg_host_password)
        -connectRetries=10
        migrate
      "
    volumes:
      - ./migrations:/flyway/sql

  # Admin tool for database
  adminer:
    image: adminer:5.4.2
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  # Web server
  caddy:
    image: caddy:2.11
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8082:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
    - ./caddy_config:/etc/caddy/
    - ./src/frontend:/srv
    - ./.data/caddy:/data
    - ./.data/caddy_runtime:/config

  api:
    build:
      context: ./src/api
    image: oatapi
    container_name: api
    restart: unless-stopped
    secrets:
      - pg_host_password
    environment:
      DB: postgres
      DB_PORT: 5432
      DB_USER: host
      DB_PASSWORD_FILE: /run/secrets/pg_host_password
      DB_NAME: postgres
    expose:
      - "9000"


secrets:
  pg_host_password:
    file: ./.secrets/postgresql/hostpw.txt